### ISSUE TITLE
关于是否自动签到问题

### ISSUE THREAD

**Issue by chainder** [t00t00-crypto/cloud189-action#1]
首先，感谢作者这个项目；其次，想请问作者，是只要点一次star就可以每天自动签到抽奖，还是每天都要点一次star？最后，再次感谢。

**Comment by tangxuchao** [comment]
我也有这个疑问。感觉并不是自动运行的

**Comment by qqzwc** [comment]
我也是，感觉并没有自动签到啊？点了star后执行了一次，一周后回来看，没有每天自动执行呢

**Comment by tangxuchao** [comment]
修改一下 readme文件 就可以自动运行了

**Comment by qqzwc** [comment]
感谢答复，确实是这样的呢。还有一个问题，原始主代码和现在您的代码，有时候签到成功，抽奖会报错，但看代码应该不会走到这步啊，不知道为什么
返回的内容有errorcode，没有执行if ("errorCode" in response.text): print(response.text)反而执行了else语句

Log如下
账号：密码：登录成功
已经签到过了，签到获得11M空间
{"errorCode":"User_Not_Chance","errorMsg":"sessionKey=52ff418b-10fb-4b55-bf36-317f03abad8d,activityId=ACT_SIGNIN,ExcuteOverLimitedNumError!"}
{"errorCode":"User_Not_Chance","errorMsg":"sessionKey=52ff418b-10fb-4b55-bf36-317f03abad8d,activityId=ACT_SIGNIN,ExcuteOverLimitedNumError!"}
Traceback (most recent call last):
  File "checkin.py", line 132, in <module>
    main()
  File "checkin.py", line 47, in main
    description = response.json()['description']
KeyError: 'description'

**Comment by pzx521521** [comment]
楼主在骗star啦, 殊不知 star 是可以点掉的 =  = 
一定要先pull 一下才会开始自动运行 => 所有的github action 都是这样的

和star没有任何关系

.github/workflows/run.yml 里面写了
  schedule:
    - cron: 0 22,14 * * *
就是22点和14点 每天运行一次
这里是美国的时间

**Comment by darkrain88** [comment]
怎么弄呢， 不自动啊

**Comment by imldy** [comment]
> 怎么弄呢，不自动啊

修改一下README然后commit，我是这样才正常自动启动的。

**Comment by yangyanch** [comment]
> > 怎么弄呢，不自动啊
> 
> 修改一下README然后commit，我是这样才正常自动启动的。

新手不太懂，是随便改一下readme么

**Comment by imldy** [comment]
> > > 怎么弄呢，不自动啊
> > 
> > 
> > 修改一下README然后commit，我是这样才正常自动启动的。
> 
> 新手不太懂，是随便改一下readme么

是的，随便加个东西，加一行空白也行，然后commit

**Comment by marshmallow2016** [comment]
> 楼主在骗star啦, 殊不知 star 是可以点掉的 = =
> 一定要先pull 一下才会开始自动运行 => 所有的github action 都是这样的
> 
> 和star没有任何关系
> 
> .github/workflows/run.yml 里面写了
> schedule:
> - cron: 0 22,14 * * *
> 就是22点和14点 每天运行一次
> 这里是美国的时间

作者本意应该是点击自己的star吧,我点了自己的star就直接运行了

**Comment by imldy** [comment]
> > 楼主在骗star啦, 殊不知 star 是可以点掉的 = =
> > 一定要先pull 一下才会开始自动运行 => 所有的github action 都是这样的
> > 和star没有任何关系
> > .github/workflows/run.yml 里面写了
> > schedule:
> > 
> > * cron: 0 22,14 * * *
> >   就是22点和14点 每天运行一次
> >   这里是美国的时间
> 
> 作者本意应该是点击自己的star吧,我点了自己的star就直接运行了

但是貌似只点star只会运行一次，无法开启自动运行。

**Comment by marshmallow2016** [comment]
> 动

可以吧,我点了star后运行了,然后修改了说明文件,保存了,就没管,刚看了下,已经在自动运行了

**Comment by liyunlongnb** [comment]
> > 怎么弄呢，不自动啊
> 
> 修改一下README然后commit，我是这样才正常自动启动的。

谢谢老哥
